### ISSUE TITLE
githubのapi通信を記述している場所をAPIラッパーライブラリ？のoctokitを使用して書き換えたいです

### ISSUE THREAD

**Issue by george0528** [ysknsid25/booby#11]
@ysknsid25 
Issue #6  を解決しようとしましたが、GithubとのAPI通信の際にクエリパラメータを直接書くことは、保守性の観点からはあまり良くないと考えました。そのため、Octokitを導入してAPIのクエリパラメータを静的に解析できるようにしたいと思っています。

CONTRIBUTING.mdにある以下の自己満足（開発者の好み）なコードリファクタリングのガイドラインが該当する可能性があるかをご確認いただけますか？

> 競合や無意味な修正を防ぐために、あらかじめ修正の内容を issue からご連絡ください。
>
> 無意味な修正とは、本質的な改善が得られない自己満足（開発者の好み）なコードリファクタリングや、ドキュメントの一部表現を変えただけのコミットを指します。

お手数をおかけしますが、ご確認いただけますと幸いです。

**Comment by ysknsid25** [comment]
@george0528 

issueありがとうございます🙏
ライブラリの導入については入れていただいて構わないと考えています。

ただ、導入後JavaScriptのstarだけで問題ないので検索結果が変わっていないことだけ確認してください🙏
