### ISSUE TITLE
PC表示時のカードが画面幅目一杯になるのでもう少し両幅に余白を持たせたい

### ISSUE THREAD

**Issue by ysknsid25** [ysknsid25/booby#5]
![image](https://github.com/ysknsid25/booby/assets/44870505/95077ddf-4a15-4b42-9e9b-24e1ea9cc859)

**Comment by kikd** [comment]
こんにちは、`good first issue`トピックからこのリポジトリを見つけました。

以下の変更を行うことで、画像の通りPC表示時に余白を付けることができます。

![image](https://github.com/ysknsid25/booby/assets/5682821/4a5002f9-6d03-4d9c-a9ae-28a0ce783a1e)


1. 余白の追加
https://github.com/ysknsid25/booby/blob/5c35f585e0fbf6d093937f84271fe9c0349a0c55/src/Components/repositoryCard.tsx#L10
この行の className に、 `w-full lg:w-3/4 xl:w-3/5` を追加して余白を追加します。

2. センタリング設定
https://github.com/ysknsid25/booby/blob/5c35f585e0fbf6d093937f84271fe9c0349a0c55/src/pages/index.tsx#L25
この行の className に、 `flex flex-wrap` を追加してカードを折り返すように設定します。




いかがでしょうか？

**Comment by ysknsid25** [comment]
@kikd 

この度は当プロジェクトに興味を持っていただいてありがとうございます！
ぜひブランチを切って、ご提案いただいた内容で修正してください。
ただ、プルリクを出す前にモバイル表示についても確認しておいていただけると助かります🙏
