### ISSUE TITLE
このリポジトリへのリンクを追加する

### ISSUE THREAD

**Issue by konojunya** [ysknsid25/booby#8]
このプロジェクト自体に貢献しやすくする目的でリポジトリへのリンクを貼るのが良いかなと思いました

**Comment by ysknsid25** [comment]
実はここにリンクがあるんです🙏

https://github.com/ysknsid25/booby/blob/5c35f585e0fbf6d093937f84271fe9c0349a0c55/src/Components/header.tsx#L7-L14

**Comment by konojunya** [comment]
本当だ、気付きませんでした、、すいません！🙏
